name: fsrvln
channels:
    - pytorch
    - nvidia
    - conda-forge
    - defaults

dependencies:
    - python=3.9
    - numpy
    - pytorch=2.4.1
    - torchvision=0.19.1
    - torchaudio=2.4.1
    - pytorch-cuda=11.8
    - faiss-gpu=1.7.2
    - pip

    - pip:
          - matplotlib==3.7.3
          - scipy
          - open3d==0.18.0
          - opencv-python
          - git+ssh://git@github.com/facebookresearch/segment-anything.git
          - torchmetrics
          - ftfy
          - tqdm
          - open-clip-torch
          - transformers
          - openai
          - plyfile
          - hydra-core
          - pyvista
          - scikit-fmm
          - pathos
          - oss2==2.9.1
          - opencv-python-headless==4.8.1.78
